### ISSUE TITLE
Good

### ISSUE THREAD

**Issue by Luoxd1996** [JooHyun-Lee/BraTs#1]
nice work.thank you very much.I want to konw where I can download BraTs 2018 dataset.Thanks!

**Comment by cv-lee** [comment]
Thanks!

To get access to the BraTS 2018 data, please use the registration page ('https://www.med.upenn.edu/sbia/brats2018/data.html')

To get access to the BraTs 2016+2017 data, you can download in 'http://medicaldecathlon.com'
