### ISSUE TITLE
Missing argument

### ISSUE THREAD

**Issue by RB61** [JooHyun-Lee/BraTs#4]
https://github.com/JooHyun-Lee/BraTs/blob/ab711a149bb45195c66c58b98badb6704d5baf79/pytorch/models/deeplab.py#L147

https://github.com/JooHyun-Lee/BraTs/blob/ab711a149bb45195c66c58b98badb6704d5baf79/pytorch/models/deeplab.py#L148

should be drop_rate=drop_rate in both lines.

**Comment by RB61** [comment]
should be drop_rate=drop_rate in both lines.

**Comment by cv-lee** [comment]
Thx ! FIXED
